#!/bin/bash

# Copyright 2017 Sergey Berezin

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop the script on the first error.
trap 'bootstrap failed on line ${LINENO}"; exit 1' ERR

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DIR}/common.sh"

echo "Current dir: ${DIR}"
echo "Root dir: ${ROOT}"

if ! which go > /dev/null; then
    echo "  WARNING: Couldn't find Go installation."
    echo "  Please download & install Go at https://golang.org/dl/"
    exit 1
fi

mkdir -p "${ROOT}/bin" "${ROOT}/pkg"

# Create bin/activate for Go environment, similar to Python's virtualenv.
cat <<EOF > "${ROOT}/bin/activate"
deactivate () {
    if [ -n "\$_OLD_GOENV_GOPATH" ]; then
	if [ "\$_OLD_GOENV_GOPATH" = "unset" ]; then
	    unset GOPATH
	else
	    GOPATH="\$_OLD_GOENV_GOPATH"
	    export GOPATH
	fi
        unset _OLD_GOENV_GOPATH
    fi
    if [ -n "\$_OLD_GOENV_PATH" ]; then
	PATH="\$_OLD_GOENV_PATH"
	export PATH
	unset _OLD_GOENV_PATH
    fi
    if [ -n "\$_OLD_GOENV_GO111MODULE" ]; then
	if [ "\$_OLD_GOENV_GO111MODULE" = "unset" ]; then
	    unset GO111MODULE
	else
	    GO111MODULE="\$_OLD_GOENV_GO111MODULE"
	    export GO111MODULE
	fi
        unset _OLD_GOENV_GO111MODULE
    fi
    # Restore shell prompt
    if [ -n "\$_OLD_GOENV_PS1" ]; then
	PS1="\$_OLD_GOENV_PS1"
	export PS1
	unset _OLD_GOENV_PS1
    fi
    if [ ! "\$1" = "nondestructive" ] ; then
	# Self destruct!
        unset -f deactivate
    fi
}

if [ -n "\$GOPATH" ]; then
    _OLD_GOENV_GOPATH="\$GOPATH"
else
    _OLD_GOENV_GOPATH="unset"
fi
export _OLD_GOENV_GO111MODULE
if [ -n "\$GO111MODULE" ]; then
    _OLD_GOENV_GO111MODULE="\$GO111MODULE"
else
    _OLD_GOENV_GO111MODULE="unset"
fi
export _OLD_GOENV_GO111MODULE
_OLD_GOENV_PATH="\$PATH"
export _OLD_GOENV_PATH
_OLD_GOENV_PS1="\$PS1"
export _OLD_GOENV_PS1

GOPATH="$ROOT"
export GOPATH
GO111MODULE="on"
export GO111MODULE
PATH="$ROOT/bin":"\$PATH"
export PATH
PS1="(go) \$PS1"
export PS1
EOF
